#ifndef DEFINITIONS_H
#define DEFINITIONS_H

///
/// placeholder txt...
///
#define PLACEHOLDERTEXT_DOMAIN "domain e.g. example.com"
#define PLACEHOLDERTEXT_IP "ip-address e.g. 8.8.8.8"
#define PLACEHOLDERTEXT_IP4 "IpV4-address e.g. 8.8.8.8"
#define PLACEHOLDERTEXT_IP_OR_CIDR "ip-address e.g. 1.1.1.1 or ip-address/cidr e.g. 1.1.1.1/24"
#define PLACEHOLDERTEXT_DOMAIN_OR_IP "domain name e.g. example.com or ip-address e.g. 1.1.1.1"
#define PLACEHOLDERTEXT_IP6 "IpV6-address e.g. 2001:4860:4860::8888"
#define PLACEHOLDERTEXT_ASN "asn number e.g. 12345"
#define PLACEHOLDERTEXT_EMAIL "email-address e.g. something@email.com"
#define PLACEHOLDERTEXT_CIDR "ip-address/cidr e.g. 1.1.1.1/24"
#define PLACEHOLDERTEXT_QUERY "query term e.g. GOOGLE"
#define PLACEHOLDERTEXT_SSLCERT "cert fingerprint(sha1 or sha256)"
#define PLACEHOLDERTEXT_PHONE "phone number e.g. +2557298984323"
#define PLACEHOLDERTEXT_USERNAME "username e.g. John Doe"
#define PLACEHOLDERTEXT_URL "url e.g. https://example.com/something"
#define PLACEHOLDERTEXT_NONE ""
#define PLACEHOLDERTEXT_NS "dns server name e.g. dns.google.com"
#define PLACEHOLDERTEXT_HOSTNAME "hostname e.g. test.example.com"
#define PLACEHOLDERTEXT_ORG "organization name e.g. GOOGLE LLC"
#define PLACEHOLDERTEXT_MX "mailserver name e.g. aspmx.l.google.com"
#define PLACEHOLDERTEXT_MAC_ADDRESS "mac address e.g. 00-05-02-34-56-78"
#define PLACEHOLDERTEXT_POC "point of contact e.g. KOSTE-ARIN"
#define PLACEHOLDERTEXT_NET "network eg"
#define PLACEHOLDERTEXT_CHECKSUM "sha256 checksum eg"
#define PLACEHOLDERTEXT_MD5 "md5 eg"
#define PLACEHOLDERTEXT_IP_OR_ASN_OR_CIDR "ip or asn or cidr"
#define PLACEHOLDERTEXT_IP_OR_ASN "ip or asn"
#define PLACEHOLDERTEXT_IP_OR_DOMAIN "ip or domain"
#define PLACEHOLDERTEXT_IP_RANGE "ip range"
#define PLACEHOLDERTEXT_IP_RANGE_OR_CIDR "ip range or cidr"
#define PLACEHOLDERTEXT_AS "as e.g. AS15169"
#define PLACEHOLDERTEXT_COUNTRY_CODE "2-digit ISO-3166 country code e.g. tz"
#define PLACEHOLDERTEXT_ANY "asn, ip, cidr, organization"
#define PLACEHOLDERTEXT_CIDR_OR_ASN "cidr or asn"
#define PLACEHOLDERTEXT_ADSENSE "google adsense id e.g. pub-5953444431482912"
#define PLACEHOLDERTEXT_NAME "domain owner's name"
#define PLACEHOLDERTEXT_UA "User-Agent"
#define PLACEHOLDERTEXT_BULK_IP "ip-address,ip-address"

#endif // DEFINITIONS_H
